spring.application.name=product-test
server.port=8080
logging.level.root=WARN
logging.level.com.example.product=DEBUG
app.environment=testing
app.api.timeout=10000

# Actuator Configuration (Test)
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
