spring.application.name=product-dev
server.port=8080
logging.level.root=DEBUG
logging.level.com.example.product=DEBUG
app.environment=development
app.api.timeout=5000

# Actuator Configuration (Development)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

# ===================================================================
# KAFKA CONFIGURATION FOR LOCAL & CONFLUENT CLOUD
# ===================================================================


# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

# Consumer Configuration  
spring.kafka.consumer.group-id=product-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.auto-offset-reset=earliest

# FOR CONFLUENT CLOUD - REPLACE VALUES AND UNCOMMENT
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="KOBXAXKO5FTSLBLB" password="cfltI+IDXbYrU2mqj3wKwsTEpAfWQVXrPlZ9wPjKNKYjPtVkfPrZEJ538QKZAWSA";
# spring.kafka.properties.schema.registry.url=https://psrc-xyz.us-east-1.provider.confluent.cloud
# spring.kafka.properties.schema.registry.basic.auth.credentials.source=USER_INFO
# spring.kafka.properties.schema.registry.basic.auth.user.info=SR_KEY:SR_SECRET

# Kafka Topics
kafka.topic.order-created=order-created
kafka.topic.order-success=order-success
kafka.topic.order-failed=order-failed

# ===================================================================
# @ConfigurationProperties
# ===================================================================
product.service.page-size=10
product.service.async-enabled=true
product.service.cache-enabled=true
product.service.scheduling-rate-ms=60000

# ===================================================================
# RESILIENCE4J CONFIGURATION
# ===================================================================

# CircuitBreaker
resilience4j.circuitbreaker.instances.kafkaProcessor.sliding-window-size=10
resilience4j.circuitbreaker.instances.kafkaProcessor.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafkaProcessor.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kafkaProcessor.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.kafkaProcessor.register-health-indicator=true

# Retry
resilience4j.retry.instances.kafkaProcessor.max-attempts=3
resilience4j.retry.instances.kafkaProcessor.wait-duration=1s

# RateLimiter
resilience4j.ratelimiter.instances.productApi.limit-for-period=100
resilience4j.ratelimiter.instances.productApi.limit-refresh-period=1s
resilience4j.ratelimiter.instances.productApi.timeout-duration=0s

# Bulkhead
resilience4j.bulkhead.instances.productApi.max-concurrent-calls=20
resilience4j.bulkhead.instances.productApi.max-wait-duration=0s
