spring.application.name=order-test
server.port=8080
logging.level.root=WARN
logging.level.com.example.order=DEBUG
app.environment=testing
app.api.timeout=10000

# Actuator - Test (Most endpoints exposed)
management.endpoints.web.exposure.include=health,info,metrics,env,threaddump,loggers
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always
